const colorVar = (cssVar) => `rgb(var(${cssVar}) / <alpha-value>)`
const colorFixed = (cssVar, alpha) => `rgb(var(${cssVar}) / ${alpha})`

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
    './*.tsx',
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: colorVar('--color-bg-primary'),
          secondary: colorVar('--color-bg-secondary'),
          tertiary: colorVar('--color-bg-tertiary'),
          elevated: colorVar('--color-bg-elevated'),
          glass: colorFixed('--color-bg-glass', 0.7),
          'glass-dark': colorFixed('--color-bg-glass-dark', 0.85),
        },
        text: {
          primary: colorVar('--color-text-primary'),
          secondary: colorVar('--color-text-secondary'),
          accent: colorVar('--color-text-accent'),
          muted: colorVar('--color-text-muted'),
          dim: colorFixed('--color-text-primary', 0.5),
        },
        accent: {
          cyan: colorVar('--color-accent-cyan'),
          'cyan-dim': colorVar('--color-accent-cyan-dim'),
          'cyan-glow': colorFixed('--color-accent-cyan', 0.4),
          teal: colorVar('--color-accent-teal'),
          'teal-dim': colorVar('--color-accent-teal-dim'),
          green: colorVar('--color-accent-green'),
          yellow: colorVar('--color-accent-yellow'),
          'yellow-dim': colorVar('--color-accent-yellow-dim'),
          orange: colorVar('--color-accent-orange'),
          red: colorVar('--color-accent-red'),
          'red-dim': colorVar('--color-accent-red-dim'),
          purple: colorVar('--color-accent-purple'),
          blue: colorVar('--color-accent-blue'),
          'blue-hover': colorVar('--color-accent-blue-hover'),
        },
        border: {
          DEFAULT: colorVar('--color-border-default'),
          subtle: colorVar('--color-border-subtle'),
          glow: colorVar('--color-border-glow'),
          active: colorVar('--color-border-active'),
          glass: colorFixed('--color-border-glass', 0.1),
        },
        discord: {
          DEFAULT: colorVar('--color-discord'),
          hover: colorVar('--color-discord-hover'),
        },
      },
      fontFamily: {
        sans: ['Rajdhani', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Consolas', 'Liberation Mono', 'Menlo', 'monospace'],
        display: ['Orbitron', 'Rajdhani', 'sans-serif'],
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        tiny: '0.65rem',
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0em',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
        tech: '0.2em',
      },
      boxShadow: {
        'glow-dot': '0 0 6px rgb(var(--color-accent-cyan) / 0.6)',
        'glow-indicator': '0 0 8px rgb(var(--color-accent-cyan) / 0.6)',
        'glow-sm': '0 0 10px rgb(var(--color-accent-cyan) / 0.3)',
        glow: '0 0 20px rgb(var(--color-accent-cyan) / 0.4)',
        'glow-lg': '0 0 30px rgb(var(--color-accent-cyan) / 0.5)',
        'glow-green': '0 0 10px rgb(var(--color-accent-green) / 0.8)',
        'glow-yellow': '0 0 10px rgb(var(--color-accent-yellow) / 0.3)',
        'glow-yellow-lg': '0 0 15px rgb(var(--color-accent-yellow) / 0.4)',
        'glow-red': '0 0 10px rgb(var(--color-accent-red) / 0.3)',
        'glow-red-soft': '0 0 15px rgb(var(--color-accent-red) / 0.1)',
        'panel-cyan': '0 0 30px rgb(var(--color-accent-cyan) / 0.18), inset 0 0 20px rgb(var(--color-accent-cyan) / 0.04)',
        'panel-cyan-soft': '0 0 40px rgb(var(--color-accent-cyan) / 0.1), 0 8px 32px rgb(0 0 0 / 0.5)',
        'panel-cyan-update': '0 0 30px rgb(var(--color-accent-cyan) / 0.2), inset 0 0 20px rgb(var(--color-accent-cyan) / 0.05)',
        'inset-cyan': 'inset 0 0 30px rgb(var(--color-accent-cyan) / 0.1)',
        'focus-cyan': '0 0 14px rgb(var(--color-accent-cyan) / 0.2)',
        'tooltip-cyan': '0 0 10px rgb(var(--color-accent-cyan) / 0.2), 0 4px 12px rgb(0 0 0 / 0.4)',
        'glow-teal': '0 0 20px rgb(var(--color-accent-teal) / 0.4)',
        'inner-glow': 'inset 0 0 20px rgb(var(--color-accent-cyan) / 0.1)',
        glass: '0 8px 32px 0 rgb(0 0 0 / 0.37)',
      },
      backgroundImage: {
        'cosmic-radial': 'radial-gradient(ellipse at center, rgb(var(--color-bg-secondary) / 1) 0%, rgb(var(--color-bg-primary) / 1) 70%)',
        'cosmic-subtle': 'radial-gradient(ellipse at 50% 0%, rgb(var(--color-accent-cyan) / 0.03) 0%, transparent 50%)',
        'panel-gradient': 'linear-gradient(180deg, rgb(var(--color-accent-cyan) / 0.05) 0%, transparent 100%)',
        'energy-line': 'linear-gradient(90deg, transparent, rgb(var(--color-accent-cyan) / 0.5), transparent)',
        scanline: 'repeating-linear-gradient(0deg, transparent, transparent 2px, rgb(var(--color-accent-cyan) / 0.03) 2px, rgb(var(--color-accent-cyan) / 0.03) 4px)',
        'grid-pattern': 'linear-gradient(rgb(var(--color-accent-cyan) / 0.05) 1px, transparent 1px), linear-gradient(90deg, rgb(var(--color-accent-cyan) / 0.05) 1px, transparent 1px)',
      },
      backgroundSize: {
        grid: '40px 40px',
      },
      animation: {
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 4s ease-in-out infinite',
        'bounce-dots': 'bounce 1.4s infinite ease-in-out both',
        'spin-slow': 'spin 2s linear infinite',
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'highlight-flash': 'highlight-flash 2s ease-out',
        'energy-flow': 'energy-flow 3s linear infinite',
        'star-twinkle': 'star-twinkle 4s ease-in-out infinite',
        'data-stream': 'data-stream 1.5s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 10px rgb(var(--color-accent-cyan) / 0.2)' },
          '50%': { boxShadow: '0 0 20px rgb(var(--color-accent-cyan) / 0.4)' },
        },
        'highlight-flash': {
          '0%': {
            boxShadow: '0 0 0 2px rgb(var(--color-accent-cyan) / 1), 0 0 20px rgb(var(--color-accent-cyan) / 0.4)',
            background: 'linear-gradient(135deg, rgb(var(--color-bg-secondary) / 1) 0%, rgb(var(--color-accent-cyan) / 0.1) 100%)',
          },
          '100%': {
            boxShadow: 'none',
            background: 'rgb(var(--color-bg-secondary) / 1)',
          },
        },
        'energy-flow': {
          '0%': { backgroundPosition: '200% center' },
          '100%': { backgroundPosition: '-200% center' },
        },
        'star-twinkle': {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '1' },
        },
        'data-stream': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
      },
      borderRadius: {
        sm: '2px',
        DEFAULT: '4px',
        md: '6px',
        lg: '8px',
        xl: '12px',
      },
    },
  },
  plugins: [],
}
